[build]
  command = "cd client/functions && npm install && cd ../ && npm run build"
  publish = "client/build"

[functions]
  directory = "client/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "22"